---
language: csharp
install:
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild build.xml
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./AliCouldOpenSearchAPI_vs2015_2.1.3/AliCloudOpenSearchAPITest/bin/Release/AliCloudOpenSearchAPITest.dll
---
language: csharp
script:
  - xbuild build45.xml