language: csharp
install:
  - nuget install NUnit.Runners -Version 3.0.1 -OutputDirectory testrunner
script:
  - xbuild build.xml
  - mono ./testrunner/NUnit.Runners.3.0.1/tools/nunit3-console.exe ./AliCouldOpenSearchAPI_vs2015_2.1.3/AliCloudOpenSearchAPITest/bin/Release/AliCloudOpenSearchAPITest.dll